### ISSUE TITLE
readmeoutputimage

### ISSUE THREAD

**Issue by diljitehg** [GwGibson/IOT1026-Assignment-1#2]
[- [](url)[[](url)]([url](`[url](url)`))](![WhatsApp Image 2023-05-18 at 3 33 20 PM](https://github.com/GwGibson/IOT1026-Assignment-1/assets/131228332/582b81a0-6cd7-4e0a-a831-93589d618266))

**Comment by GwGibson** [comment]
You are supposed to embed the image in your repo description
